# Copyright Jiaqi Liu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: Bump Version (Patch version) By GitHub Tags

"on":
  workflow_call:
    inputs:
      user:
        description: The username of the GitHub user who has write access to push tags
        type: string
        required: true
      email:
        description: The emails linked to the user on GitHub
        type: string
        required: true

jobs:
  bump-version:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Download auto-version bump scripts
      run: |
        git clone https://github.com/QubitPi/hashicorp-aws.git ../hashicorp-aws
        cp ../hashicorp-aws/.github/tag-for-release.bash .github/
        cp ../hashicorp-aws/.github/upversion.py .github/
    - name: Tag for release
      run: |
        git config --global user.name ${{ inputs.user }}
        git config --global user.email ${{ inputs.email }}
        .github/tag-for-release.bash
